import { ComponentBase } from "./template-builder";

export interface ComponentBaseInput {
  afterDestroyed: (callback: Function) => void;
  afterMounted: (callback: Function) => void;
  on: (event: string, callback: Function) => Function;
  ref: () => () => HTMLElement | null;
  send: (event: string, data: any) => void;
  stateUpdater: (callback: Function) => (e?: Event, ...args: any[]) => Promise<void>;
}

interface Options {
  [key: string]: any;
}

export interface Templater extends AllElements {
  component: (callback: (i: ComponentBaseInput) => any) => ComponentBase;
  custom: ElementInput;
}
type ElementInput = (...args: any) => void;

export interface AllElements {
  a: ElementInput;
  abbr: ElementInput;
  acronym: ElementInput;
  address: ElementInput;
  area: ElementInput;
  article: ElementInput;
  aside: ElementInput;
  audio: ElementInput;
  b: ElementInput;
  base: ElementInput;
  bdi: ElementInput;
  bdo: ElementInput;
  big: ElementInput;
  blockquote: ElementInput;
  body: ElementInput;
  br: ElementInput;
  button: ElementInput;
  canvas: ElementInput;
  caption: ElementInput;
  center: ElementInput;
  cite: ElementInput;
  code: ElementInput;
  col: ElementInput;
  colgroup: ElementInput;
  comment: ElementInput;
  custom: ElementInput;
  data: ElementInput;
  datalist: ElementInput;
  dd: ElementInput;
  del: ElementInput;
  details: ElementInput;
  dfn: ElementInput;
  dialog: ElementInput;
  div: ElementInput;
  dl: ElementInput;
  dt: ElementInput;
  em: ElementInput;
  embed: ElementInput;
  fieldset: ElementInput;
  figcaption: ElementInput;
  figure: ElementInput;
  font: ElementInput;
  footer: ElementInput;
  form: ElementInput;
  frame: ElementInput;
  frameset: ElementInput;
  generate: () => string;
  h1: ElementInput;
  h2: ElementInput;
  h3: ElementInput;
  h4: ElementInput;
  h5: ElementInput;
  h6: ElementInput;
  head: ElementInput;
  header: ElementInput;
  hr: ElementInput;
  html: ElementInput;
  i: ElementInput;
  iframe: ElementInput;
  img: ElementInput;
  input: ElementInput;
  ins: ElementInput;
  kbd: ElementInput;
  label: ElementInput;
  legend: ElementInput;
  li: ElementInput;
  link: ElementInput;
  main: ElementInput;
  map: ElementInput;
  mark: ElementInput;
  meta: ElementInput;
  meter: ElementInput;
  nav: ElementInput;
  noscript: ElementInput;
  object: ElementInput;
  ol: ElementInput;
  optgroup: ElementInput;
  option: ElementInput;
  output: ElementInput;
  p: ElementInput;
  param: ElementInput;
  picture: ElementInput;
  pre: ElementInput;
  progress: ElementInput;
  q: ElementInput;
  rp: ElementInput;
  rt: ElementInput;
  ruby: ElementInput;
  s: ElementInput;
  samp: ElementInput;
  script: ElementInput;
  section: ElementInput;
  select: ElementInput;
  small: ElementInput;
  source: ElementInput;
  span: ElementInput;
  strong: ElementInput;
  style: ElementInput;
  sub: ElementInput;
  summary: ElementInput;
  sup: ElementInput;
  table: ElementInput;
  tbody: ElementInput;
  td: ElementInput;
  template: ElementInput;
  text: (text: string | number) => string;
  textarea: ElementInput;
  tfoot: ElementInput;
  th: ElementInput;
  thead: ElementInput;
  time: ElementInput;
  title: ElementInput;
  tr: ElementInput;
  track: ElementInput;
  u: ElementInput;
  ul: ElementInput;
  var: ElementInput;
  video: ElementInput;
  wbr: ElementInput;
  xmp: ElementInput;
}
